### ISSUE TITLE
Configurable Timeouts

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/puppeteer-mocha#5]

**Comment by alex-kuck** [comment]
In addition to the **timeouts** provided to `mocha` via **package.json**, which target the timeout for single tests, maybe we should also make timeouts for `page.waitForNavigation` configurable. We could provide a default value of `0`, which disables the timeout, e.g.:

`page.waitForNavigation({timeout: 0, waitUntil: 'networkidle'})`

c.f. [Puppeteer Issue #782](https://github.com/GoogleChrome/puppeteer/issues/782) and [merged PR](https://github.com/GoogleChrome/puppeteer/pull/887)

**Comment by mkoertgen** [comment]
For now, i will opt to support mocha.opts from `./test` again.

**Comment by mkoertgen** [comment]
Also support customized `./test/options.js` (if any)

**Comment by mkoertgen** [comment]
Network timeouts cannot be configured globally. The default idletimeout of 1s should be ok.

**Comment by mkoertgen** [comment]
Fixed with https://github.com/awesome-inc/puppeteer-mocha/commit/ccaddb7752d67844d8f07049ee5e33df8cb52cfb
