### ISSUE TITLE
How to use within a standard angular-cli project?

### ISSUE THREAD

**Issue by jowave** [awesome-inc/puppeteer-mocha#6]

**Comment by mkoertgen** [comment]
Need to look further into it. Meanwhile you might check out 

https://github.com/Quramy/angular-puppeteer-demo/

which shows how to move from karma to testing with puppeteer

**Comment by mkoertgen** [comment]
Here is another post on using puppeteer with the karma-chrome-launcher plugin

“Automating Karma and headless Chrome with Puppeteer” @rogeriopvl https://medium.com/@rogeriopvl/automating-karma-and-headless-chrome-with-puppetteer-51ce8f6a78b0

The would be more suitable for a straight angular project

**Comment by mkoertgen** [comment]
Love to involve @alex-kuck here

**Comment by alex-kuck** [comment]
@jowave Are you interested in using Puppeteer with Mocha or just switching from PhantomJS to Puppeteer?

According to [this issue](https://github.com/angular/angular-cli/issues/4071) there is no support planned for other runners than Karma right now.

**Comment by DanielP42** [comment]
Interesting idea.

**Comment by alex-kuck** [comment]
You can use Puppeteer by following these steps:

**1. Install Dependencies:**

```sh
npm i --save-dev puppeteer karma-chrome-launcher
```

**2. Update `karma.conf.js`:**

```javascript
process.env.CHROME_BIN = require('puppeteer').executablePath();
...
module.exports = function (config) {
  config.set({
    ...
    customLaunchers: {
      ChromeHeadless:  {
        base:   'Chrome',
        flags:  [
          '--headless',
          '--disable-gpu',
          '--no-sandbox',
          '--remote-debugging-port=9222'
        ],
      }
    },
    ...
    browsers: ['ChromeHeadless']
    ...
  });
};
```

**Comment by jowave** [comment]
Thanks, I will try it out.
